package projeto_sorvil.model;


public enum Genero {
	ADMINISTRACAO, ARTES, AUTOAJUDA, AVENTURA, BIOGRAFIA, CONTO, DICIONARIO, 
	DIREITO, ECONIMIA, FANTASIA, FICCAO_CIENTIFICA, FILOSOFIA, GEOGRAFIA, HISTORIA,
	HUMOR, LINGUISTICA, MEDICINA, POESIA, POLICIAL, PSICOLOGIA, RELIGIAO,
	ROMANCE, SUSPENSE, TERROR, TURISMO

}
